project:
  type: website

website:
  title: "Stephen J Eglen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - talks.qmd
      - research.qmd
      - software.qmd
      - open.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



