project:
  type: website
  output-dir: docs
  
website:
  title: "Stephen J Eglen"
  favicon: favicon-32x32.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publications.qmd
      - research.qmd
      - software.qmd
      - open.qmd

filters:
  - auto-dark      

format:
  html:
    theme:
      light: cosmo
    css: styles.css
    toc: true



