---
title: "Publications"
---

After each reference, *Paper* links to papers; *Info* to further information
about that paper, including code and data.

### Preprints




Lyngholm D, Sterratt DC, Johannes Hjorth JJ, Willshaw DJ, Eglen SJ,
Thompson ID (2019) Measuring and modelling the emergence of order in
the mouse retinocollicular projection. bioRxiv:713628
[*Paper*](https://doi.org/10.1101/713628)
[*Info*](http://github.com/sje30/b2).


Lonborg AV, Eglen SJ (2017) A mechanistic model of the spatial
interaction between blue cones and blue cone bipolar cells in macaque
retina. bioRxiv:129643 
[*Paper*](http://biorxiv.org/content/early/2017/04/22/129643)


Cutts CS, Eglen SJ (2016) A Bayesian framework for comparing the
structure of spontaneous correlated activity recorded under different
conditions. bioRxiv:037358
[*Paper*](http://biorxiv.org/content/early/2016/01/19/037358)

Reprints for papers already published are also available by searching
on [biorxiv](http://biorxiv.org/search/eglen).

### 2025


Akarca D, Dunn AWE, Hornauer PJ, Ronchi S, Fiscella M, Wang C,
Terrigno M, Jagasia R, Vértes PE, Mierau SB, Paulsen O, Eglen SJ,
Hierlemann A, Astle DE, Schröter M (2025) Homophilic wiring principles
underpin neuronal network topology in vitro. Elife 14
[*Paper*](http://dx.doi.org/10.7554/eLife.85300)
[*Code*](https://github.com/DanAkarca/MEA_generative_models).


### 2024

Sit TPH et al. (2024) MEA-NAP: A flexible network analysis pipeline
 for neuronal 2D and 3D organoid multielectrode recordings. Cell Rep
 Methods 4:100901
 [Paper](https://pubmed.ncbi.nlm.nih.gov/39520988/)
 [Code](https://github.com/SAND-Lab/MEA-NAP)
 
 
Schmausser M, Holland A, Beresford-Webb J, Eglen SJ, Manning K, Aman
L, Kronhaus D, Koenig J (2024) Effects of long-term transcutaneous
auricular vagus nerve stimulation on circadian vagal activity in
people with Prader-Willi Syndrome: A case-series. Res Dev Disabil
154:104855 
[Paper](https://pubmed.ncbi.nlm.nih.gov/39405838/)



### 2023

Edinburgh T, Ercole A, Eglen S (2023) Bayesian model selection for
multilevel models using integrated likelihoods. PLoS One 18:e0280046 
[Paper](http://dx.doi.org/10.1371/journal.pone.0280046)
[Code](https://github.com/tedinburgh/model-evidence-with-integrated-likelihood)




### 2022

N Gale, J Rodger, M Small, S Eglen (2022)
  Analysis of activity dependent development of topographic maps in
  neural field theory with short time scale dependent plasticity.
	Mathematical Neuroscience and Applications 2
	[*Paper*](https://mna.episciences.org/8390)
	[*Code*](https://github.com/Nick-Gale/Neural_Field_Theory_Topopgraphic_Development).

T Edinburgh, SJ Eglen, P Thoral, P Elbers, A Ercole (2022) Sepsis-3
  criteria in AmsterdamUMCdb: open-source code
  implementation. Gigabyte 2022:1–7
	[*Paper*](https://gigabytejournal.com/articles/45)
	[*Code*](https://github.com/tedinburgh/sepsis3-amsterdamumcdb).

### 2021


Edinburgh T, Eglen SJ, Ercole A (2021) Causality indices for bivariate
time series data: A comparative review of performance. Chaos 31:083111
[*Paper*](https://doi.org/10.1063/5.0053519)
[*Code*](https://github.com/tedinburgh/causality-review).

Edinburgh T, Smielewski P, Czosnyka M, Cabeleira M, Eglen SJ, Ercole A
(2021) DeepClean: Self-Supervised Artefact Rejection for Intensive
Care Waveform Data Using Deep Generative Learning. In: Intracranial
Pressure and Neuromonitoring XVII, pp 235–241 Acta Neurochirurgica
Supplement. 
[*Paper*](https://arxiv.org/abs/1908.03129).


Nüst D, Eglen SJ (2021) CODECHECK: an Open Science initiative for the
independent execution of computations underlying research articles
during peer review to improve reproducibility. F1000Res 10:253
[*Paper*](http://dx.doi.org/10.12688/f1000research.51738.2).

Eglen SJ (2021) [Re] Spatial constraints underlying the retinal
mosaics of two types of horizontal cells in cat and macaque. Rescience
C 6:22  [*Paper*](https://zenodo.org/record/5347786).

### 2020

Nüst D, Sochat V, Marwick B, Eglen SJ, Head T, Hirst T, Evans BD
(2020) Ten simple rules for writing Dockerfiles for reproducible data
science. PLoS Comput Biol 16:e1008316 
[*Paper*](http://dx.doi.org/10.1371/journal.pcbi.1008316).


Keeley PW, Eglen SJ, Reese BE (2020) From Random to Regular: Variation
in the Patterning of Retinal Mosaics. J Comp Neurol 528:2135-2160.
[*Paper*](http://dx.doi.org/10.1002/cne.24880).
[*Preprint*](http://arxiv.org/abs/1910.10210).


### 2019
Hyvärinen T, Hyysalo A, Kapucu FE, Aarnos L, Vinogradov A, Eglen SJ,
Ylä-Outinen L, Narkilahti S (2019) Functional characterization of
human pluripotent stem cell-derived cortical networks differentiated
on laminin-521 substrate: comparison to rat cortical cultures. Sci Rep
9:17125 [Paper](https://doi.org/10.1038/s41598-019-53647-8).


Cotterill E, Eglen SJ (2019) Burst Detection Methods. In: In Vitro
Neuronal Networks, From Culturing Methods to Neuro-Technological
Applications, pp 185–206 [*Paper*](https://arxiv.org/abs/1802.01287).

### 2018


Eglen SJ, Mounce R, Gatto L, Currie AM, Nobis Y (2018) Recent developments in scholarly publishing to improve research practices in the life sciences. Emerg Top Life Sci 2:775–778 [*Paper*](http://www.emergtoplifesci.org/lookup/doi/10.1042/ETLS20180172)

Gelfman S, Wang Q, Lu Y-F, Hall D, Bostick C, Dhindsa R, Halvorsen M,
Melodi McSweeney K, Cotterill E, Edinburgh T, Petrovski S, Boland MJ,
Allen AS, Goldstein DB, Eglen SJ (2018) meaRtools: an R package for
the analysis of neuronal networks recorded on
microelectrode arrays.  PLOS Comput Biol 14:e1006506.
[*Paper*](https://doi.org/10.1371/journal.pcbi.1006506)
[*Code*](https://cran.r-project.org/web/packages/meaRtools/index.html)


### 2017

Eglen SJ, Marwick B, Halchenko YO, Hanke M, Sufi S, Gleeson P,
Angus Silver R, Davison AP, Lanyon L, Abrams M, Wachtler T, Willshaw
DJ, Pouzat C, Poline J-B (2017) Toward standard practices for sharing
computer code and programs in neuroscience. Nat Neurosci 20:770–773.  [*Paper*](http://www.nature.com/neuro/journal/v20/n6/full/nn.4550.html)


Savier E, Eglen SJ, Bathélémy A, Perraut M, Pfrieger FW, Lemke G,
Reber M (2017) A molecular mechanism for the topographic
alignment of convergent neural maps. eLife Sciences 6:e20470.
[*Paper*](http://dx.doi.org/10.7554/eLife.20470)
[*Info*](https://github.com/michaelreber/3-step-Map-Aligment-Model/)


### 2016

Perez-Riverol Y, Gatto L, Wang R, Sachsenberg T, Uszkoreit J, da Veiga Leprevost F, Fufezan C, Ternent T, Eglen SJ, Katz DS, Pollard TJ, Konovalov A, Flight RM, Blin K, Vizcaino JA (2016) Ten simple rules for taking advantage of git and github. PLoS Comput Biol 12:e1004947.
[*Paper*](http://dx.doi.org/10.1371/journal.pcbi.1004947)
[*Info*](https://github.com/ypriverol/github-paper)



Cotterill E, Charlesworth P, Thomas CW, Paulsen O, Eglen SJ (2016) A
comparison of computational methods for detecting bursts in neuronal
spike trains and their application to human stem cell-derived neuronal
networks. J Neurophysiol 116:306-321.
[*Paper*](http://jn.physiology.org/content/116/2/306)
[*Info*](https://github.com/ellesec/burstanalysis)
<!-- http://dx.doi.org/10.1152/jn.00093.2016  -->
<!-- github archived at http://dx.doi.org/10.5281/zenodo.50312 -->

Eglen SJ (2016) Bivariate spatial point patterns in the retina: a
reproducible review. Journal de la Société Française de Statistique
157:33–48.
[*Paper*](http://journal-sfds.fr/article/view/518)
[*Info*](http://github.com/sje30/eglen2015)

Gjorgjieva J, Evers JF, Eglen SJ (2016) Homeostatic activity-dependent
tuning of recurrent networks for robust propagation of activity. J
Neurosci 36:3722–3734.  [*Paper*](http://dx.doi.org/10.1523/JNEUROSCI.2511-15.2016)

Cotterill E, Hall D, Wallace K, Mundy WR, Eglen SJ, Shafer TJ (2016)
Characterization of Early Cortical Neural Network Development in
Multiwell Microelectrode Array Plates. J Biomol Screen 21:510-519
[*Paper*](http://dx.doi.org/10.1177/1087057116640520) [*Info*](http://github.com/sje30/EPAmeadev)



Leiwe MN, Hendry AC, Bard AD, Eglen SJ, Lowe AS, Thompson ID (2016)
Geniculo-cortical projection diversity revealed within the mouse
visual thalamus. PLoS One
11:e0144846. [*Paper*](http://dx.doi.org/10.1371/journal.pone.0144846)

Charlesworth P, Morton A, Eglen SJ, Komiyama NH, Grant SGN (2016)
Canalization of genetic and pharmacological perturbations in
developing primary neuronal activity patterns. Neuropharmacology
100:47–55. [*Paper*](http://dx.doi.org/10.1016/j.neuropharm.2015.07.027)
[*Info*](http://damtp.cam.ac.uk/user/sje30/papers/charlesworth2015_data.pdf)

### 2015

Hjorth JJJ, Savier E, Sterratt DC, Reber M, Eglen SJ (2015b)
Estimating the location and size of retinal injections from orthogonal
images of an intact retina. BMC Neurosci 16:80.
[*Paper*](http://dx.doi.org/10.1186/s12868-015-0217-8)
[*Info*](https://github.com/Hjorthmedh/IntactEye)

Budd JML, Cuntz H, Eglen SJ, Krieger P (2015) Editorial: Quantitative
Analysis of Neuroanatomy. Front Neuroanat 9:143.
[*Paper*](http://dx.doi.org/10.3389/fnana.2015.00143)

Hjorth JJJ, Sterratt DC, Cutts CS, Willshaw DJ, Eglen SJ (2015a)
Quantitative assessment of computational models for retinotopic map
formation. Dev Neurobiol 75:641–666.
[*Paper*](http://dx.doi.org/10.1002/dneu.22241)
[*Info*](https://github.com/Hjorthmedh/RetinalMap)


Charlesworth P, Cotterill E, Morton A, Grant SGN, Eglen SJ (2015)
Quantitative differences in developmental profiles of spontaneous
activity in cortical and hippocampal cultures. Neural Dev 10:1.
[*Paper*](http://www.neuraldevelopment.com/content/10/1/1/)
[*Info*](https://github.com/sje30/g2chvc)




### 2014

Cutts CS, Eglen SJ (2014) Detecting pairwise correlations in spike
trains: an objective comparison of methods and application to the
study of retinal waves. J Neurosci 34:14288–14303.
[*Paper*](http://dx.doi.org/10.1523/JNEUROSCI.2767-14.2014)
[*Info*](https://github.com/CCutts/Detecting_pairwise_correlations_in_spike_trains)


Eglen S (2014a) Open access: sharing your data is easier than you think. Nature 510:340.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/eglen2014_correspondence.pdf)


Maccione A, Hennig MH, Gandolfo M, Muthmann O, van Coppenhagen J, Eglen SJ, Berdondini L, Sernagor E (2014) Following the ontogeny of retinal waves: pan-retinal recordings of population dynamics in the neonatal mouse. J Physiol 592:1545–1563.
[*Paper*](http://dx.doi.org/10.1113/jphysiol.2013.262840)
[*Info*](http://www.damtp.cam.ac.uk/user/sje30/waverepo)

Eglen SJ (2014b) Retinotopic Development, Models of. In: Encyclopedia of Computational Neuroscience, pp 1–4. Springer New York.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/eglen2013_enc.pdf)
[DOI](http://doi.org/10.1007/978-1-4614-6675-8_406)

Schottdorf M, Eglen SJ, Wolf F, Keil W (2014) Can retinal ganglion cell dipoles seed iso-orientation domains in the visual cortex? PLoS One 9:e86139.
[*Paper*](http://dx.doi.org/10.1371/journal.pone.0086139)

Eglen SJ, Weeks M, Jessop M, Simonotto J, Jackson T, Sernagor E (2014)
A data repository and analysis framework for spontaneous neural
activity recordings in developing retina. Gigascience 3:3.
[*Paper*](http://dx.doi.org/10.1186/2047-217X-3-3)
[*Info*](http://github.com/sje30/waverepo)


### 2013

Gjorgjieva J, Berni J, Evers JF, Eglen SJ (2013) Neural circuits for
peristaltic wave propagation in crawling Drosophila larvae: analysis
and modeling. Front Comput Neurosci 7:24.
[*Paper*](http://dx.doi.org/10.3389/fncom.2013.00024)

### 2012

Hore VRA, Troy JB, Eglen SJ (2012) Parasol cell mosaics are unlikely
to drive the formation of structured orientation maps in primary
visual cortex. Vis Neurosci 29:283–299.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/hore2012.pdf)
<!-- (http://dx.doi.org/10.1017/S0952523812000338)  -->


Keeley PW, Sliff BJ, Lee SCS, Fuerst PG, Burgess RW, Eglen SJ, Reese
BE (2012) Neuronal clustering and fasciculation phenotype in Dscam-
and Bax-deficient mouse retinas. J Comp Neurol 520:1349–1364.
[*Paper*](http://dx.doi.org/10.1002/cne.23033)

Chabrol FP, Eglen SJ, Sernagor E (2012) GABAergic control of retinal
ganglion cell dendritic development. Neuroscience 227:30–43.
[*Paper*](http://dx.doi.org/10.1016/j.neuroscience.2012.09.040)

### 2011

Gjorgjieva J, Eglen SJ (2011) Modeling developmental patterns of
spontaneous activity. Curr Opin Neurobiol 21:679–684.
[*Paper*](http://ukpmc.ac.uk/articles/PMC3184139)

### 2009

Gjorgjieva J, Toyoizumi T, Eglen SJ (2009) Burst-time-dependent
plasticity robustly guides ON/OFF segregation in the lateral
geniculate nucleus. PLoS Comput Biol 5:e1000618.
[*Paper*](http://www.ploscompbiol.org/doi/pcbi.1000618)



Godfrey KB, Eglen SJ, Swindale NV (2009) A multi-component model of
the developing retinocollicular pathway incorporating axonal and
synaptic growth. PLoS Comput Biol 5:e1000600.
[*Paper*](http://www.ploscompbiol.org/doi/pcbi.1000600)

Eglen SJ (2009) A Quick Guide to Teaching R Programming to
Computational Biology Students. PLoS Comput Biol 5:e1000482.
[*Paper*](http://www.ploscompbiol.org/doi/pcbi.1000482)

### 2008

Eglen SJ, Lofgreen DD, Raven MA, Reese BE (2008) Analysis of spatial
relationships in three dimensions: tools for the study of nerve cell
patterning. BMC Neurosci 9:68.
[*Paper*](http://www.biomedcentral.com/1471-2202/9/68)


Eglen SJ, Wong JCT (2008) Spatial constraints underlying the retinal mosaics of two types of horizontal cells in cat and macaque. Vis Neurosci 25:209–214.
[*Paper*](http://arxiv.org/pdf/1208.0986.pdf)

### 2006

Eglen SJ (2006) Development of regular cellular spacing in the retina:
theoretical models. Math Med Biol 23:79–99.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/eglen2006.pdf)


Sernagor E, Eglen SJ, Harris WA, Wong ROL eds. (2006) Retinal
Development. Cambridge University Press.


### 2005 

Eglen SJ, Diggle PJ, Troy JB (2005) Homotypic constraints dominate
positioning of on- and off-center beta retinal ganglion cells. Vis
Neurosci 22:859–871.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/eglen2005.pdf)

Kishi M, Kummer TT, Eglen SJ, Sanes JR (2005) LL5beta: a regulator of
postsynaptic differentiation identified in a screen for synaptically
enriched transcripts at the neuromuscular junction. J Cell Biol
169:355–366.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/kishi2005.pdf)

### 2003

Eglen SJ, Raven MA, Tamrazian E, Reese BE (2003b) Dopaminergic
amacrine cells in the inner nuclear layer and ganglion cell layer
comprise a single functional retinal mosaic. J Comp Neurol
466:343–355.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/eglen2003.pdf)


Sernagor E, Young C, Eglen SJ (2003) Developmental Modulation of
Retinal Wave Dynamics: Shedding Light on the GABA Saga. J Neurosci
23:7621–7629.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/sernagor2003_jn.pdf)


Raven MA, Eglen SJ, Ohab JJ, Reese BE (2003) Determinants of the
exclusion zone in dopaminergic amacrine cell mosaics. J Comp Neurol
461:123–136.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/raven2003.pdf)

Eglen SJ, Galli-Resta L, Reese BE (2003a) Theoretical models of
retinal mosaic formation. In: Modeling neural development (van Ooyen
A, ed), pp 133–150. MIT Press.

Demas J, Eglen SJ, Wong ROL (2003) Developmental loss of synchronous
spontaneous activity in the mouse retina is independent of visual
experience. J Neurosci 23:2851–2860.
[*Paper*](http://www.jneurosci.org/cgi/pmidlookup?view=long&pmid=12684472)

### 2002 

Lee CW, Eglen SJ, Wong ROL (2002) Segregation of on and off
Retinogeniculate Connectivity Directed by Patterned Spontaneous
Activity. J Neurophysiol 88:2311–2321.
[*Paper*](http://jn.physiology.org/cgi/reprint/88/5/2311)
[*Info*](http://jn.physiology.org/cgi/content/full/88/5/2311/DC1)

### 2000

Eglen SJ, van Ooyen A, Willshaw DJ (2000) Lateral cell movement driven
by dendritic interactions is sufficient to form retinal
mosaics. Network 11:103–118.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/eglen2000.pdf)
[*Info*](http://www.damtp.cam.ac.uk/user/sje30/mosaics/index.html)


Sernagor E, Eglen SJ, O’Donovan MJ (2000) Differential Effects of
Acetylcholine and Glutamate Blockade on the Spatiotemporal Dynamics of
Retinal Waves. J Neurosci 20:RC56.
[*Paper*](http://www.jneurosci.org/cgi/content/abstract/20/2/RC56)
[*Info*](http://www.damtp.cam.ac.uk/user/sje30/chick-waves/index.html)

### 1999

Eglen SJ (1999) The role of retinal waves and synaptic normalization
in retinogeniculate development. Philos Trans R Soc Lond B Biol Sci
354:497–506.
[*Paper*](http://www.damtp.cam.ac.uk/user/sje30/papers/eglen1999.pdf)

### 1997

Eglen S, Bray A, Stone J (1997) Unsupervised discovery of
invariances. Network: Computation in Neural Systems 8:441–452.
[*Paper*](http://doi.org/10.1088/0954-898X_8_4_006)

### 1996

Tate AR, Watson D, Eglen S, Arvanitis TN, Thomas EL, Bell JD (1996)
Automated feature extraction for the classification of human in
vivo13C NMR spectra using statistical pattern recognition and
wavelets. Magn Reson Med 35:834–840.
[*Paper*](https://paperpile.com/app/p/a0aac56b-3a3c-002c-b201-438556b845fd)

<!-- Bowns L, Eglen SJ (1994) Extraction of non-fourier orientation information for texture classification. Investigative Opthalmology and Visual Science 35:1406. -->
